[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
cache = true
solc_version = "0.8.26"
gas_reports = ["*"]
remappings = [
    "@openzeppelin/openzeppelin-contracts/=node_modules/@openzeppelin/openzeppelin-contracts/",
    "@openzeppelin/openzeppelin-contracts-upgradeable/=node_modules/@openzeppelin/openzeppelin-contracts-upgradeable/",
    "@zetachain/protocol-contracts/=node_modules/@zetachain/protocol-contracts/",
    "@zetachain/standard-contracts/=node_modules/@zetachain/standard-contracts/",
    "@zetachain/toolkit/=node_modules/@zetachain/toolkit/",
    "@uniswap/v2-core/=node_modules/@uniswap/v2-core/",
    "@uniswap/v2-periphery/=node_modules/@uniswap/v2-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
